config/routes.rb
Uniiv::Application.routes.draw do

  get 'scenario/new'
  get 'static_page/uniiv'
  get 'static_page/story'
  get 'static_page/team'
  get 'static_page/getinvolved'
  get 'static_page/suggestions'
  get 'static_page/bugreports'
  get 'static_page/cookies'
  get 'static_page/privacy'
  get 'static_page/termsofuse'
  get 'user_settings/index'
  get 'group/index'
  get 'group/graph_embed'
  get 'program/index'
  post 'user_programs/removeProgram'

  get 'graph/index'
  get 'test/index'

  root to: 'welcome#index'

  get 'header' => 'welcome#header'

  namespace :admin do
    get 'utils' => 'utils#index', :as => :utils_home
    namespace :utils do
      get 'course/requirements' => 'course_requirements#index', :as => :check_course_requirements_completed
      get 'course/requirements/:id/none' => 'course_requirements#mark_as_none', :as => :course_requirement_mark_none
      get 'course/requirements/:id/input' => 'course_requirements#input_requirement', :as => :course_requirement_input
      get 'course/requirements/:id/subject_input_requirement' => 'course_requirements#subject_input_requirement', :as => :course_requirement_subject_input
      post 'course/requirements/:id/input' => 'course_requirements#save_requirement', :as => :course_requirement_input_save
      get 'course/loader/load' => 'course_loader#new', :as => :course_load_new
      post 'course/loader/load' => 'course_loader#load', :as => :course_load_create
      post 'course/loader/load_all' => 'course_loader#load_all', :as => :course_load_all
    end
  end

  devise_for :users, :controllers => {registrations: 'registration/registrations',
                                      passwords: 'registration/passwords',
                                      sessions: 'registration/sessions'}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  post 'user/emails/new' => 'user/emails#create', :as => :user_email_new
  post 'user/emails/set_as_default' => 'user/emails#set_as_default', :as => :user_email_set_as_default
  post 'user/emails/remove' => 'user/emails#remove', :as => :user_email_remove

  get 'user/university/show' => 'user_university#show', :as => :user_university_show
  get 'user/university/edit' => 'user_university#edit', :as => :user_university_edit
  post 'user/university/edit' => 'user_university#update', :as => :user_university_update
  post 'user/university/delete' => 'user_university#delte', :as => :user_university_delete

  get 'user/faculty/show' => 'user_faculty#show', :as => :user_faculty_show
  get 'user/faculty/edit' => 'user_faculty#edit', :as => :user_faculty_edit
  post 'user/faculty/edit' => 'user_faculty#update', :as => :user_faculty_update
  post 'user/faculty/delete' => 'user_faculty#delte', :as => :user_faculty_delete

  get 'user/program/show' => 'user_programs#show', :as => :user_programs_show
  get 'user/program/new' => 'user_programs#new', :as => :user_programs_new
  get 'user/program/selectversion' => 'user_programs#select_version', :as => :user_program_select_version
  post 'user/program/new' => 'user_programs#create', :as => :user_programs_create
  post 'user/program/delete' => 'user_programs#delete', :as => :user_programs_delete

  get 'explore' => 'explore#index', :as => :explore
  get 'explore/program' => 'explore#program', :as => :explore_programs
  get 'explore/courses' => 'explore#courses', :as => :explore_courses
  get 'explore/courses/next_page' => 'explore#courses_list', :as => :explore_courses_next_page
  get 'explore/subjects' => 'explore#subjects', :as => :explore_subjects

  get 'contactus' => 'contactus_form#new', :as => :contactus
  post 'contactus' => 'contactus_form#create'

  get 'test' => 'test#index'

  get 'university/search/autocomplete' => 'university#search_autocomplete', :as => :university_search_autocomplete

  get 'faculty/search/autocomplete' => 'faculty#search_autocomplete', :as => :faculty_search_autocomplete

  get 'program/:program_id/version/new' => 'program/version#new', :as => :program_version_new
  post 'program/:program_id/version/new' => 'program/version#create'
  get 'program/:program_id/version/list' => 'program/version#list', :as => :program_version_list
  get 'program/version/change-version' => 'program/version#change_version', :as => :program_version_change
  get 'program/version/:id' => 'program/version#show', :as => :program_version
  get 'program/version/:id/edit' => 'program/version#edit', :as => :program_version_edit
  patch 'program/version/:id/edit' => 'program/version#update'
  delete 'program/version/delete' => 'program/version#delete', :as => :program_version_delete

  namespace :program, path: '' do
    resources :programs
    get 'search/autocomplete' => 'programs#search_autocomplete', as: :program_search_autocomplete
  end
  namespace :program do
    resources :groups do
      resources :restrictions, module: :group do
        collection do
          get 'list'
        end
      end
    end
  end
  scope path: 'program/group', module: 'course' do
    resources :subject_course_lists
  end

  get 'mygraph' => 'graph#show', :as => :user_graph
  get 'mygraph/data' => 'graph#user_data', :as => :user_graph_data
  get 'graph/program/:id/data' => 'graph#program_graph_data', :as => 'program_graph_data'
  get 'graph/program/:id' => 'graph#show_program_graph', :as => 'program_graph'

  get 'course/search/data' => 'course#search_json', :as => :search_course_json
  get 'course/search/autocomplete' => 'course#search_autocomplete', :as => :search_course_autocomplete
  get 'course/search/autocomplete' => 'course#search_autocomplete', :as => :course_autocomplete
  get 'course/search/show' => 'course#search_list', :as => :search_course_list
  get 'course/:id', to: 'course#show', as: :course
  get 'course/:id/show' => 'course#show'
  get 'course/:id/json' => 'course#json'

  get 'course/:course_id/review/' => 'course_review#index', :as => :course_reviews
  get 'course/:course_id/review/:id/show' => 'course_review#show', :as => :course_review
  get 'course/:course_id/review/new' => 'course_review#new', :as => 'course_review_new'
  post 'course/:course_id/review/new' => 'course_review#create', :as => 'course_review_create'
  get 'course/:course_id/review/new/graph/embed' => 'course_review#new_graph_embed', :as => :course_review_new_graph_embed, :defaults => {:graph_embed => true}
  post 'course/:course_id/review/new/graph/embed' => 'course_review#create', :as => :course_review_create_graph_embed, :defaults => {:graph_embed => true}

  get 'education' => 'user_dashboard#index', :as => :user_education
  get 'education/selection' => 'user_dashboard#selection', :as => :user_education_selection
  get 'education/status' => 'user_dashboard#education_status', :as => :user_education_status_content
  get 'education/course_taking_content' => 'user_dashboard#user_course_taking_content', :as => :user_education_course_taking_content
  get 'education/course_completed_content' => 'user_dashboard#user_course_completed_content', :as => :user_education_course_completed_content

  scope :module => 'user' do

    get 'user/course/sort' => 'course_planner#index', :as => :user_sort_course
    post 'user/course/take' => 'course_planner#take_course', :as => :take_course_planner
    post 'user/courses/remove' => 'course_planner#untake_course', :as => :untake_course_planner

    post 'user/course/untake' => 'course#remove', :as => :user_untake_course
    get 'course/:course_id/complete' => 'course#complete_show', :as => :user_complete_course
    get 'course/:course_id/complete/graph/embed' => 'course#complete_show', :as => 'user_complete_course_ge', :defaults => {:graph_embed => true}
    post 'course/:course_id/complete' => 'course#complete_create', :as => :user_mark_complete_course
    post 'course/:course_id/complete/graph/embed' => 'course#complete_create', :as => 'user_mark_complete_course_ge', :defaults => {:graph_embed => true}
    get 'course/:course_id/take' => 'course#take_show', :as => :user_take_course
    get 'course/:course_id/take/graph/embed' => 'course#take_show', :as => 'user_take_course_graph_embed', :defaults => {:graph_embed => true}
    post 'course/:course_id/take' => 'course#take_create', :as => 'user_take_course_create'
    post 'course/:course_id/take/graph/embed' => 'course#take_create', :as => 'user_take_course_create_graph_embed', :defaults => {:graph_embed => true}

    get 'user/advanced-standings' => 'advanced_standing#index', :as => :user_advanced_standings
    post 'user/advanced-standings/create' => 'advanced_standing#create', :as => :user_advanced_standings_create
    post 'user/advanced-standings/remove' => 'advanced_standing#remove', :as => :user_advanced_standings_remove
    post 'user/advanced-standings/setcredit' => 'advanced_standing#set_credit', :as => :user_advanced_standings_setcredit

    get 'scenario/new' => 'scenario#new', :as => :user_new_scenario
    post 'scenario/remove' => 'scenario#remove', :as => :user_remove_scenario
    post 'scenario/setmain' => 'scenario#set_main', :as => :user_setmain_scenario
  end

  scope :module => 'utils' do
    get 'utils/finalgradecalculator' => 'final_grade_calculator#index', :as => :utils_fgc
    get 'utils/finalgradecalculator/search' => 'final_grade_calculator#search', :as => :utils_fgc_search
    get 'utils/finalgradecalculator/course/:id' => 'final_grade_calculator#show', :as => :utils_fgc_course
    post 'utils/finalgradecalculator/course/:id/create_grade' => 'final_grade_calculator#create_grade', :as => :utils_fgc_create_grade
    post 'utils/finalgradecalculator/course/:id/edit_grade_name' => 'final_grade_calculator#edit_grade_name', :as => :utils_fgc_edit_grade_name
    post 'utils/finalgradecalculator/course/:id/edit_grade_value' => 'final_grade_calculator#edit_grade_value', :as => :utils_fgc_edit_grade_value
    post 'utils/finalgradecalculator/course/:id/remove_grade' => 'final_grade_calculator#remove_grade', :as => :utils_fgc_remove_grade

app/controllers/course/subject_course_lists_controller.rb
class Course::SubjectCourseListsController < ApplicationController
  load_and_authorize_resource

  def show
    if request.xhr?
      render partial: 'list_courses', layout: false
    else
      render 'show'
    end
  end

  def new
    @subject_course_list.group = Program::Group.find(params[:group_id])
  end

  def create
    if @subject_course_list.save
      if params[:saveandedit]
        redirect_to edit_subject_course_list_path(@subject_course_list)
      else
        redirect_to edit_program_group_path(@subject_course_list.group)
      end
    else
      flash[:alert] = @subject_course_list.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @subject_course_list.assign_attributes(subject_course_list_params)
    if @subject_course_list.save
      if params[:saveandedit]
        redirect_to edit_subject_course_list_path(@subject_course_list)
      else
        redirect_to edit_program_group_path(@subject_course_list.group)
      end
    else
      flash[:alert] = @subject_course_list.errors.full_messages
      render :edit
    end
  end

  def destroy
    @subject_course_list.destroy
    if request.xhr?
      return_json 'deleted'
    else
      _redirect_to :back
    end
  end

  private
  def subject_course_list_params
    params.require(:subject_course_list).permit(:level, :operation, :group_id).merge(subject: Course::Subject.find_by_name(params[:subject_course_list][:subject]))
  end


  def _
    @subject_course_list = Course::SubjectCourseList.find(params[:id])
  end
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  before_action :setup

  def setup
    authorize! :read, Course::Course
  end

  def show
    @course = Course::Course.find(params[:id])
    render :layout => false if request.xhr?
  end

  def json
    course = Course::Course.find(params[:id])
    render :json => course.as_json
  end

  def search_list
    params[:need_reload] ||= false
    @courses = search_course
    render :layout => false
  end

  def search_json
    courses = search_course
    render :json => courses.to_json
  end

  def search_autocomplete
    courses = search_course
    json = {}
    json[:query] = params[:q]
    suggestions = []
    json[:suggestions] = suggestions
    courses.each do |course|
      suggestion = {}
      suggestion[:value] = course.to_s + ' ' + course.name
      suggestion[:data] = course.id
      suggestions << suggestion
    end
    render :json => json.to_json
  end

  def search_course
    limit = params[:limit]
    query = params[:q]
    prerequisites = false
    if query.downcase.start_with?('pre:')
      query = query[4..-1]
      prerequisites = true
    end
    search = Course::Course.search do
      fulltext query
      paginate(:page => 1, :per_page => limit) unless limit.nil?
      without(:course_scenario_ids, current_scenario.id) if params[:only_not_taking]
      with(:course_scenario_ids, current_scenario.id) if params[:only_taking]
      without(:user_ids, current_user.id) if params[:only_not_completed]
      with(:user_ids, current_user.id) if params[:only_completed]
    end
    if prerequisites
      search.results.first.list_dependencies(include_corequisite: false)
    else
      search.results
    end
  end
end

app/helpers/course_helper.rb
module CourseHelper

  def get_course_css_class(course)
    state = course.get_course_state(current_scenario)
    case state
      when CourseState::COMPLETED
        'course_completed'
      when CourseState::TAKING
        return 'course_taking'
      when CourseState::AVAILABLE
        return 'course_available'
      when CourseState::UNAVAILABLE
        return 'course_unavailable'
      else
        return 'course_unavailable'
    end
  end

  def get_expr_html(expr, template = nil)
    get_node_html(expr.node, template)
  end

  def get_node_html(node, template = nil)
    r = ''
    return '' if node.operation.nil?
    if node.operation == NodeOperation::NODE
      course = node.course
      puts 'N: ' + node.id.to_s
      if template.nil?
        r = r + "<a href='#{course_path(:id => course.id)}' data-id='#{course.id}' data-type='course' class='#{get_course_css_class(course)} underline_link'>#{course.to_s}</a>"
      else
        r += render template, :course => course
      end
    else
      r = r + ' (' + node.nodes.map { |k| "#{get_node_html(k, template)}" }.join(' ' + node.operation + ' ') + ') '
    end
    r
  end

  def user_remove_course_form(course)

  end

  def user_courses_dnd_zone(courses, path, params: '', no_drop: false, details: true)
    render 'user/course/course_dnd_zone', update_path: path, courses: courses, params: params, no_drop: no_drop, details: details
  end

  def course_list_item(course, details: true)

    invalid_time = if course.is_a? UserTakingCourse
                     !course.is_time_valid?
                   else
                     false
                   end
    render 'course/sort_course_list_item', :course => course, :invalid_time => invalid_time, details: details
  end

  def course_status_icon(course)
    state = course.get_course_state(current_scenario)
    content = ''
    case state
      when CourseState::COMPLETED
        content = content_tag 'span', '', :class => 'glyphicon glyphicon-ok-circle bluetext',
                              :title => t('course.completed'), 'rel' => 'tooltip', 'data-placement' => 'left'
      when CourseState::TAKING
        content = content_tag 'span', '', :class => 'glyphicon glyphicon-time yellowtext',
                              :title => t('course.taking'), 'rel' => 'tooltip', 'data-placement' => 'left'
      when CourseState::AVAILABLE
        content = content_tag 'span', '', :class => 'glyphicon glyphicon-thumbs-up greentext',
                              :title => t('course.available'), 'rel' => 'tooltip', 'data-placement' => 'left'
      when CourseState::UNAVAILABLE
        content = content_tag 'span', '', :class => 'glyphicon glyphicon-ban-circle redtext',
                              :title => t('course.unavailable'), 'rel' => 'tooltip', 'data-placement' => 'left'
    end
    content
  end

  def course_card(course, useajax: false)
    render 'course/course_card', course: course, useajax: useajax
  end

end

app/helpers/user/course_helper.rb
module User::CourseHelper

  def user_course_buttons(course, useajax = false, delete_parent: '')
    if user_signed_in?
      if current_user.has_completed_course?(course)
        user_course_completed = current_user.completed_courses.where(:course_id => course.id).first
        render 'user/course/course_completed_buttons', course: user_course_completed, useajax: useajax, delete_parent: delete_parent
      elsif current_scenario.plan_to_take_course?(course)
        user_course_taking = current_scenario.taking_courses.where(:course_id => course.id).first
        render 'user/course/course_taking_buttons', course: user_course_taking, useajax: useajax, delete_parent: delete_parent
      else
        render 'user/course/course_default_buttons', course: course, useajax: useajax, delete_parent: delete_parent
      end
    else

    end
  end

  def complete_course_inline_form(user_taking_course, params= {})
    course_complete = UserCompletedCourse.new
    grades = current_user.university.grading_system.entities

    course_complete.semester = user_taking_course.semester
    course_complete.year = user_taking_course.year
    html = {}
    html[:class] = 'form-inline'
    html[:class] += ' useajax' if params[:useajax]
    html['data-delete-parent'] = params[:delete_parent] unless params[:delete_parent].nil?
    html['data-reload']= params[:reload] unless params[:reload].nil?
    render :partial => 'user/course/complete_inline_form', :locals =>
        {:course => user_taking_course.course, :course_complete => course_complete, :grades => grades, :html => html}
  end
end

app/views/course/_course_card.html.slim
.shadow-box.course-card.link data-href=course_path(course)
  .course-card-info
    div
      strong= course
    span.ellipsis= course.name
  .course-card-buttons
    = user_course_buttons(course, useajax, delete_parent: '.course-card')

app/views/course/_course_expr_sortable.html.erb
<li class='dependency <%= 'notsortable' if current_scenario.plan_to_take_course?(course) or current_user.has_completed_course?(course) %>' style='display: inline-block'>
  <div data-course-id="<%= course.id %>" data-need-reload=true>
    <span class='<%= get_course_css_class(course) %>'><%= course.to_s %></span>

    <div style="display: inline-block"><%= link_to course_path(course), :target => '_blank' do %>
          <button class='btn btn-info btn-sm'>
            <span class='glyphicon glyphicon-info-sign'></span>
          </button>
      <% end %></div>
  </div>
</li>

app/views/course/_course_list.html.slim
.course-list.container-fluid
  - courses.each do |course|
    = render :partial => 'course/course_list_item', :locals => {:course => course}

app/views/course/_course_list_item.html.slim
.row.course-list-item
  .course-status.text-md.vertical-align
    - if current_user.has_completed_course?(course)
      span class='glyphicon glyphicon-ok-circle greentext' title='You have completed this course' rel='tooltip'
    - elsif current_scenario.plan_to_take_course?(course)
      span class='glyphicon glyphicon-screenshot yellowtext' title='You are taking this course' rel='tooltip'
  .course-text.vertical-align
    = link_to course.get_detail_name, course_path(course)
  .course-buttons
    = user_course_buttons(course)

app/views/course/_sort_course_list_item.html.erb
<% if details %>
    <li class='<%= 'invalid-time' if invalid_time %>'>
      <div class='container-fluid' data-course-id='<%= course.course.id %>'>
        <div class='row'>
          <div class='col-md-9'>
            <h5><%= course.course.to_s + ' - ' + course.course.name %></h5>
          </div>
          <div class='col-md-1 col-md-offset-2'>
            <button class='rotatecontent btn btn-success' data-container='#dependencies_<%= course.course.id %>'>
              <span class='glyphicon glyphicon-chevron-down'></span>
            </button>
          </div>
        </div>
        <div id='dependencies_<%= course.course.id %>' class='row dependencies' style='display: none'>
          <div class='col-md-10 col-md-offset-1'>
            <div>
              <div><label><%= t('prerequisites') %>: </label></div>
              <% if course.course.prerequisite.nil? %>
                  <%= t('none') %>
              <% else %>
                  <div style="display: inline-block">
                    <ul class='sortable no-drop duplicate' data-group='course'>
                      <%= raw get_expr_html(course.course.prerequisite, 'course/course_expr_sortable') %>
                    </ul>
                  </div>
              <% end %>
            </div>
            <div>
              <div><label><%= t('corequisites') %>: </label></div>
              <% if course.course.corequisite.nil? %>
                  <%= t('none') %>
              <% else %>
                  <div style="display: inline-block">
                    <ul class='sortable no-drop duplicate' style="display: inline-block" data-group='course'>
                      <%= raw get_expr_html(course.course.corequisite, 'course/course_expr_sortable') %>
                    </ul>
                  </div>
              <% end %>
            </div>
          </div>
          <div class='col-md-1'>
            <a href='<%= course_path(course.course) %>' class='btn btn-info' target='_blank'><span class='whitetext glyphicon glyphicon-info-sign'></span></a>
          </div>
        </div>
      </div>
    </li>
<% else %>
    <li>
      <div data-course-id='<%= course.id %>' data-need-reload=true>
        <h5><%= course.to_s %></h5>
      </div>
    </li>
<% end %>

app/views/course/graph_embed.html.erb
<% @course_status = "" %>
<% if current_user.is_taking_course?(@course) %>
    <% c = current_scenario.get_by_course(@course) %>
    <% unless c.semester.nil? or c.year.nil? %>
        <% @course_status = c.semester.to_s.capitalize + ' ' + c.year.to_s %>
    <% end %>
<% elsif current_user.has_completed_course?(@course) %>
    <% c = UserCompletedCourse.all.where(:user_id => current_user.id).where(:course_id => @course.id).first %>
    <% unless c.semester.nil? or c.year.nil? %>
        <% @course_status = c.semester.to_s.capitalize + ' ' + c.year.to_s %>
    <% end %>
<% end %>


<div>
  <span class='<%= get_course_css_class(@course) %>'><%= link_to (@course.subject.to_s + ' ' + @course.code.to_s), course_path(@course), 'data-type' => 'ext' %></span><br>
  <%= @course_status %>
</div>
<div><%= @course.name %></div>

<div><%= @course.hours %> Hours, <%= @course.credit %> Credits</div>

<div>Prerequisites:
  <% if @course.prerequisite.nil? %>
      None.
  <% else %>
      <%= raw(get_expr_html(@course.prerequisite)) %>
  <% end %>
</div>
<div>Corequisites:
  <% if @course.corequisite.nil? %>
      None.
  <% else %>
      <%= raw(get_expr_html(@course.corequisite)) %>
  <% end %>
</div>

<br>

<div class='text-center'>
  <div class='btn-group'>
    <button class='btn btn-info' rel='popover' data-toggle='popover' data-content='<%= @course.description %>' data-placement='left'>
      <span class='whitetext glyphicon glyphicon-eye-open'></span></button>
    <% if current_user.is_taking_course?(@course) or current_user.has_completed_course?(@course) %>
        <% coursesindb = current_scenario.taking_courses.to_a %>
        <% coursesindb.concat(current_user.completed_courses.to_a) %>
        <% variable = -1 %>
        <% coursesindb.each do |cid| %>
            <% if cid.course == @course %>
                <% variable = cid %>
            <% end %>
        <% end %>
        <% if current_user.is_taking_course?(@course) %>
            <a href='<%= user_complete_course_ge_path(@course) %>' class='btn btn-success' rel='tooltip' data-toggle='tooltip' title='Mark Completed'><span class='whitetext glyphicon glyphicon-ok-sign'></span></a>
            <a href='' class='btn btn-danger' rel='tooltip' data-type='ext' data-toggle='tooltip' title='Remove'><span class='whitetext glyphicon glyphicon-remove-sign'></span></a>
        <% else %>
            <% unless current_user.reviewed_course?(@course) %>
                <a href='<%= course_review_new_graph_embed_path(@course) %>' class='btn btn-success' rel='tooltip' data-toggle='tooltip' title='Review'><span class='whitetext glyphicon glyphicon-comment'></span></a>
            <% end %>
            <a href='' class='btn btn-danger' rel='tooltip' data-type='ext' data-toggle='tooltip' title='Remove'><span class='whitetext glyphicon glyphicon-remove-sign'></span></a>
        <% end %>
    <% else %>
        <a href='<%= user_take_course_graph_embed_path(@course) %>' class='btn btn-warning' rel='tooltip' data-toggle='tooltip' title='Mark In-Progress'><span class='whitetext glyphicon glyphicon-plus-sign'></span></a>
        <a href='<%= user_complete_course_ge_path(@course) %>' class='btn btn-success' rel='tooltip' data-toggle='tooltip' title='Mark Completed'><span class='whitetext glyphicon glyphicon-ok-sign'></span></a>
    <% end %>
    <% if @course.reviews.size >= 0 %>
        <a class='btn btn-info' href='<%= course_path(@course) %>' data-type='ext' rel='tooltip' data-toggle='tooltip' title='There are <%= @course.reviews.size %> reviews.'><span class='whitetext glyphicon glyphicon-bullhorn'></span></a>
    <% end %>
  </div>
</div>
<div>
  <div class='text-xxl text-center' style="margin-top: 20px">
    <%= raw(course_status_icon(@course)) %>
  </div>
</div>
<script type='text/javascript' src='/assets/tooltiprun.js'></script>

app/views/course/search_list.html.erb
<% @courses.each do |course| %>
    <li>

      <div data-course-id='<%= course.id %>' data-type='new' data-need-reload=<%= params[:need_reload] %>>
        <h5><%= course.to_s %>
        </h5>
      </div>
    </li>
<% end %>

app/views/course/show.html.erb
<div class='row' style="margin-top: 10px">
  <div class='col-md-8'>
    <h3 class='<%= get_course_css_class(@course) %> underline_link'>
      <%= link_to @course.get_short_name, course_path(@course) %>
    </h3>
  </div>
  <div class='col-md-4'>
    <% if user_signed_in? %>
        <%= user_course_buttons(@course) %>
    <% end %>
  </div>
</div>

<% if current_user.is_taking_course?(@course) %>
    <% c = current_scenario.get_by_course(@course) %>
    <% unless c.semester.nil? or c.year.nil? %>
        <p><%= t('course.inprogress.label') %> <%= c.semester.to_s.capitalize %> <%= c.year %></p>
    <% end %>
<% end %>

<p><%= @course.name %></p>

<p><%= @course.hours %> Hours, <%= @course.credit %> Credits</p>

<p><%= @course.description %></p>

<p>Prerequisites:
  <% if @course.prerequisite.nil? %>
      None.
  <% else %>
      <%= raw(get_expr_html(@course.prerequisite)) %>
  <% end %>
</p>

<p>Corequisites:
  <% if @course.corequisite.nil? %>
      None.
  <% else %>
      <%= raw(get_expr_html(@course.corequisite)) %>
  <% end %>
</p>

<div>
  <div class='text-xxl text-center' style="margin-top: 20px">
    <%= raw(course_status_icon(@course)) %>
  </div>
</div>

<% reviews = @course.reviews %>
<% if reviews.size > 0 %>
    <hr>
    <h2>Reviews (<%= reviews.size %>)</h2>
    <% reviews.each do |r| %>
        <div>
          <p><%= r.user.email.split('@')[0] %></p>

          <p><%= r.comment %></p>

          <div class='row'>
            <% r.ratings.each do |s| %>
                <div class='col-md-4'>
                  <label><%= s.criteria.name %>: </label>
                  <span class='badge'><%= s.score %></span>
                </div>
            <% end %>
          </div>
        </div>
    <% end %>
<% end %>