config/routes.rb
Uniiv::Application.routes.draw do

  get 'scenario/new'
  get 'static_page/uniiv'
  get 'static_page/story'
  get 'static_page/team'
  get 'static_page/getinvolved'
  get 'static_page/suggestions'
  get 'static_page/bugreports'
  get 'static_page/cookies'
  get 'static_page/privacy'
  get 'static_page/termsofuse'
  get 'user_settings/index'
  get 'group/index'
  get 'group/graph_embed'
  get 'program/index'
  post 'user_programs/removeProgram'

  get 'graph/index'
  get 'test/index'

  root to: 'welcome#index'

  get 'header' => 'welcome#header'

  namespace :admin do
    get 'utils' => 'utils#index', :as => :utils_home
    namespace :utils do
      get 'course/requirements' => 'course_requirements#index', :as => :check_course_requirements_completed
      get 'course/requirements/:id/none' => 'course_requirements#mark_as_none', :as => :course_requirement_mark_none
      get 'course/requirements/:id/input' => 'course_requirements#input_requirement', :as => :course_requirement_input
      get 'course/requirements/:id/subject_input_requirement' => 'course_requirements#subject_input_requirement', :as => :course_requirement_subject_input
      post 'course/requirements/:id/input' => 'course_requirements#save_requirement', :as => :course_requirement_input_save
      get 'course/loader/load' => 'course_loader#new', :as => :course_load_new
      post 'course/loader/load' => 'course_loader#load', :as => :course_load_create
      post 'course/loader/load_all' => 'course_loader#load_all', :as => :course_load_all
    end
  end

  devise_for :users, :controllers => {registrations: 'registration/registrations',
                                      passwords: 'registration/passwords',
                                      sessions: 'registration/sessions'}
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  post 'user/emails/new' => 'user/emails#create', :as => :user_email_new
  post 'user/emails/set_as_default' => 'user/emails#set_as_default', :as => :user_email_set_as_default
  post 'user/emails/remove' => 'user/emails#remove', :as => :user_email_remove

  get 'user/university/show' => 'user_university#show', :as => :user_university_show
  get 'user/university/edit' => 'user_university#edit', :as => :user_university_edit
  post 'user/university/edit' => 'user_university#update', :as => :user_university_update
  post 'user/university/delete' => 'user_university#delte', :as => :user_university_delete

  get 'user/faculty/show' => 'user_faculty#show', :as => :user_faculty_show
  get 'user/faculty/edit' => 'user_faculty#edit', :as => :user_faculty_edit
  post 'user/faculty/edit' => 'user_faculty#update', :as => :user_faculty_update
  post 'user/faculty/delete' => 'user_faculty#delte', :as => :user_faculty_delete

  get 'user/program/show' => 'user_programs#show', :as => :user_programs_show
  get 'user/program/new' => 'user_programs#new', :as => :user_programs_new
  get 'user/program/selectversion' => 'user_programs#select_version', :as => :user_program_select_version
  post 'user/program/new' => 'user_programs#create', :as => :user_programs_create
  post 'user/program/delete' => 'user_programs#delete', :as => :user_programs_delete

  get 'explore' => 'explore#index', :as => :explore
  get 'explore/program' => 'explore#program', :as => :explore_programs
  get 'explore/courses' => 'explore#courses', :as => :explore_courses
  get 'explore/courses/next_page' => 'explore#courses_list', :as => :explore_courses_next_page
  get 'explore/subjects' => 'explore#subjects', :as => :explore_subjects

  get 'contactus' => 'contactus_form#new', :as => :contactus
  post 'contactus' => 'contactus_form#create'

  get 'test' => 'test#index'

  get 'university/search/autocomplete' => 'university#search_autocomplete', :as => :university_search_autocomplete

  get 'faculty/search/autocomplete' => 'faculty#search_autocomplete', :as => :faculty_search_autocomplete

  get 'program/:program_id/version/new' => 'program/version#new', :as => :program_version_new
  post 'program/:program_id/version/new' => 'program/version#create'
  get 'program/:program_id/version/list' => 'program/version#list', :as => :program_version_list
  get 'program/version/change-version' => 'program/version#change_version', :as => :program_version_change
  get 'program/version/:id' => 'program/version#show', :as => :program_version
  get 'program/version/:id/edit' => 'program/version#edit', :as => :program_version_edit
  patch 'program/version/:id/edit' => 'program/version#update'
  delete 'program/version/delete' => 'program/version#delete', :as => :program_version_delete

  namespace :program, path: '' do
    resources :programs
    get 'search/autocomplete' => 'programs#search_autocomplete', as: :program_search_autocomplete
  end
  namespace :program do
    resources :groups do
      resources :restrictions, module: :group do
        collection do
          get 'list'
        end
      end
    end
  end
  scope path: 'program/group', module: 'course' do
    resources :subject_course_lists
  end

  get 'mygraph' => 'graph#show', :as => :user_graph
  get 'mygraph/data' => 'graph#user_data', :as => :user_graph_data
  get 'graph/program/:id/data' => 'graph#program_graph_data', :as => 'program_graph_data'
  get 'graph/program/:id' => 'graph#show_program_graph', :as => 'program_graph'

  get 'course/search/data' => 'course#search_json', :as => :search_course_json
  get 'course/search/autocomplete' => 'course#search_autocomplete', :as => :search_course_autocomplete
  get 'course/search/autocomplete' => 'course#search_autocomplete', :as => :course_autocomplete
  get 'course/search/show' => 'course#search_list', :as => :search_course_list
  get 'course/:id', to: 'course#show', as: :course
  get 'course/:id/show' => 'course#show'
  get 'course/:id/json' => 'course#json'

  get 'course/:course_id/review/' => 'course_review#index', :as => :course_reviews
  get 'course/:course_id/review/:id/show' => 'course_review#show', :as => :course_review
  get 'course/:course_id/review/new' => 'course_review#new', :as => 'course_review_new'
  post 'course/:course_id/review/new' => 'course_review#create', :as => 'course_review_create'
  get 'course/:course_id/review/new/graph/embed' => 'course_review#new_graph_embed', :as => :course_review_new_graph_embed, :defaults => {:graph_embed => true}
  post 'course/:course_id/review/new/graph/embed' => 'course_review#create', :as => :course_review_create_graph_embed, :defaults => {:graph_embed => true}

  get 'education' => 'user_dashboard#index', :as => :user_education
  get 'education/selection' => 'user_dashboard#selection', :as => :user_education_selection
  get 'education/status' => 'user_dashboard#education_status', :as => :user_education_status_content
  get 'education/course_taking_content' => 'user_dashboard#user_course_taking_content', :as => :user_education_course_taking_content
  get 'education/course_completed_content' => 'user_dashboard#user_course_completed_content', :as => :user_education_course_completed_content

  scope :module => 'user' do

    get 'user/course/sort' => 'course_planner#index', :as => :user_sort_course
    post 'user/course/take' => 'course_planner#take_course', :as => :take_course_planner
    post 'user/courses/remove' => 'course_planner#untake_course', :as => :untake_course_planner

    post 'user/course/untake' => 'course#remove', :as => :user_untake_course
    get 'course/:course_id/complete' => 'course#complete_show', :as => :user_complete_course
    get 'course/:course_id/complete/graph/embed' => 'course#complete_show', :as => 'user_complete_course_ge', :defaults => {:graph_embed => true}
    post 'course/:course_id/complete' => 'course#complete_create', :as => :user_mark_complete_course
    post 'course/:course_id/complete/graph/embed' => 'course#complete_create', :as => 'user_mark_complete_course_ge', :defaults => {:graph_embed => true}
    get 'course/:course_id/take' => 'course#take_show', :as => :user_take_course
    get 'course/:course_id/take/graph/embed' => 'course#take_show', :as => 'user_take_course_graph_embed', :defaults => {:graph_embed => true}
    post 'course/:course_id/take' => 'course#take_create', :as => 'user_take_course_create'
    post 'course/:course_id/take/graph/embed' => 'course#take_create', :as => 'user_take_course_create_graph_embed', :defaults => {:graph_embed => true}

    get 'user/advanced-standings' => 'advanced_standing#index', :as => :user_advanced_standings
    post 'user/advanced-standings/create' => 'advanced_standing#create', :as => :user_advanced_standings_create
    post 'user/advanced-standings/remove' => 'advanced_standing#remove', :as => :user_advanced_standings_remove
    post 'user/advanced-standings/setcredit' => 'advanced_standing#set_credit', :as => :user_advanced_standings_setcredit

    get 'scenario/new' => 'scenario#new', :as => :user_new_scenario
    post 'scenario/remove' => 'scenario#remove', :as => :user_remove_scenario
    post 'scenario/setmain' => 'scenario#set_main', :as => :user_setmain_scenario
  end

  scope :module => 'utils' do
    get 'utils/finalgradecalculator' => 'final_grade_calculator#index', :as => :utils_fgc
    get 'utils/finalgradecalculator/search' => 'final_grade_calculator#search', :as => :utils_fgc_search
    get 'utils/finalgradecalculator/course/:id' => 'final_grade_calculator#show', :as => :utils_fgc_course
    post 'utils/finalgradecalculator/course/:id/create_grade' => 'final_grade_calculator#create_grade', :as => :utils_fgc_create_grade
    post 'utils/finalgradecalculator/course/:id/edit_grade_name' => 'final_grade_calculator#edit_grade_name', :as => :utils_fgc_edit_grade_name
    post 'utils/finalgradecalculator/course/:id/edit_grade_value' => 'final_grade_calculator#edit_grade_value', :as => :utils_fgc_edit_grade_value
    post 'utils/finalgradecalculator/course/:id/remove_grade' => 'final_grade_calculator#remove_grade', :as => :utils_fgc_remove_grade

app/models/fgc/group.rb
class Fgc::Group < ActiveRecord::Base
  belongs_to :prediction, :class_name => Fgc::Prediction, :touch => true
  has_many :grades, :class_name => Fgc::Grade
  has_many :percents, :class_name => Fgc::Percent, :dependent => :destroy

  def scheme_percent(scheme)
    scheme = scheme.id unless scheme.is_a? Numeric
    percents.each do |percent|
      if percent.scheme.id == scheme
        return percent
      end
    end
    nil
  end
end

app/models/program.rb
module Program
  def self.table_name_prefix
    'program_'
  end
end

app/models/program/group/restriction_type.rb
class Program::Group::RestrictionType < ActiveRecord::Base
  def to_s
    name
  end
end

app/models/programs_type.rb
class ProgramsType < ActiveRecord::Base

  def to_s
    name
  end
end

app/controllers/program/group/restrictions_controller.rb
#Controller to manage the group restriction(Min group, min credit)
class Program::Group::RestrictionsController < ApplicationController
  load_and_authorize_resource :group, class: 'Program::Group'
  load_and_authorize_resource :through => :group, class: 'Program::Group::Restriction', except: :list

  def list
    authorize! :read, Program::Group::Restriction
    render partial: 'list', locals: {group: @group}
  end

  def create
    @restriction.group = @group
    if @restriction.save
      return_json('Restriction added with success')
    else
      return_json(@restriction.errors.full_messages, success: false)
    end
  end

  def destroy
    if @restriction.destroy
      return_json('Restriction deleted with success')
    else
      return_json(@restriction.errors.full_messages, success: false)
    end
  end

  def restriction_params
    params.require(:restriction).permit(:value, :type_id)
  end
  def reload_restriction
    @restriction = Program::Group::Restriction.find(params[:id])
    @group = Program::Group.find(params[:group_id])
  end
end

app/controllers/program/groups_controller.rb
class Program::GroupsController < ApplicationController
  load_and_authorize_resource

  def show
    render layout: false if request.xhr?
  end

  def new
    @group.parent = find_parent
  end

  def create
    @group.parent = find_parent
    if @group.save
      if params[:saveandedit]
        redirect_to edit_program_group_path(@group)
      else
        redirect_to_parent
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    @group.assign_attributes(group_params)
    if @group.save
      if params[:saveandedit]
        redirect_to edit_program_group_path(@group)
      else
        redirect_to_parent
      end
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to :back
  end

  private
  def find_parent
    if params.key?(:parent_type) and params.key?(:parent_id)
      params[:parent_type].constantize.find(params[:parent_id])
    else
      fail ActiveRecord::RecordNotFound
    end
  end

  def redirect_to_parent
    if @group.parent.is_a? Program::Version
      redirect_to edit_program_program_path(@group.parent)
    elsif @group.parent.is_a? Program::Group
      redirect_to edit_program_group_path(@group.parent)
    end
  end


  def group_params
    params.require(:program_group).permit(:name)
  end

  def reload_group
    @group = Program::Group.find(params[:id])
  end
end

app/controllers/program/programs_controller.rb
class Program::ProgramsController < ApplicationController
  load_and_authorize_resource

  def index
    @search = search
    @fullwidth = true
  end

  def show
    @program_version = @program.last_version
    if request.xhr?
      render layout: false
    end
  end

  def search_autocomplete
    programs = search.results
    json = {}
    json[:query] = params[:q]
    suggestions = []
    json[:suggestions] = suggestions
    programs.each do |program|
      suggestion = {}
      suggestion[:value] = program.to_long_s
      suggestion[:data] = program.id
      suggestions << suggestion
    end
    render :json => json.to_json
  end

  def new
  end

  def create

    if @program.save
      if params[:saveandedit]
        redirect_to edit_program_program_path(@program)
      else
        redirect_to program_programs_path
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @program.update(program_params)
      flash[:notice] = t('program.updated.success')
      if params[:saveandedit]
        redirect_to edit_program_program_path(@program)
      else
        redirect_to program_programs_path
      end
    else
      render :edit
    end
  end

  def destroy
    @program.destroy
    redirect_to :back
  end

  private

  def program_params
    params.require(:program_program).permit(:name, :type_id, :faculty_id)
  end

  def search
    ProgramSearcher.new(params).search
  end

  def reload_program
    @program = Program::Program.find(params[:id])
  end
end

app/controllers/program/version_controller.rb
class Program::VersionController < ApplicationController

  def show
    authorize! :view, Program::Version
    @program_version = Program::Version.find(params[:id])
  end

  def change_version
    redirect_to program_version_path(id: params[:version_id])
  end

  def new
    authorize! :create, Program::Version
    @program = Program::Program.find(params[:program_id])
    @program_version = Program::Version.new
  end

  def create
    authorize! :create, Program::Version
    @program = Program::Program.find(params[:program_id])
    template = Program::Version.find_by_id(params[:template])
    @program_version = if template.nil?
                         Program::Version.new
                       else
                         template.new_copy
                       end
    @program_version.assign_attributes(version_params)
    @program_version.program = @program
    if @program_version.save
      redirect_to program_program_path(@program)
    else
      render :new
    end
  end

  def edit
    @program_version = Program::Version.find(params[:id])
    authorize! :update, @program_version
  end

  def update
    @program_version = Program::Version.find(params[:id])
    authorize! :update, @program_version
    @program_version.assign_attributes(version_params)
    if @program_version.save
      redirect_to program_program_path(@program_version.program)
    else
      render :edit
    end
  end


  def list
  end

  def delete
    @program_version = Program::Version.find(params[:id])
    authorize! :delete, @program_version
    @program_version.destroy
    redirect_or_json :destination => program_path(@program_version.program),
                     :success => true, :message => 'program.version.delete.success'
  end

  #Show the difference bettween 2 version of the same program
  def diff
    @old_version = Program::Version.find(params[:old_version_id])
    @version = Program::Version.find(params[:version_id])
  end

  def version_params
    params.require(:program_version).permit(:start_year, :end_year)
  end
end

app/helpers/program/group_restrictions_helper.rb
module Program::GroupRestrictionsHelper
end

app/helpers/program/version_helper.rb
module Program::VersionHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/program/group/_form.html.erb
<%= form_for @program_group, :url => url do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <div class="form-group">
      Requirement to complete this group(Minmimum number of credit, class program, ...)<br>
      For example if you are required to complete 9 credit in the spcified courses then put type to be min_credit and value to 9
    </div>
    <div class="form-group">
      <%= f.submit :Save, :class => 'btn btn-default' %>
      <%= f.submit 'Save and edit', :name => :saveandedit, :class => 'btn btn-default' %>
    </div>

    <%= hidden_field_tag :parent_id, @program_group.groupparent.id %>
    <%= hidden_field_tag :parent_type, @program_group.groupparent.class.to_s %>
<% end %>

app/views/program/group/_group_subject_courses.html.erb
<hr>
<div>
  <% subject_courses.each do |subject_course| %>
      <div class='row'>
        <div class='col-md-9'>
          <h4> <%= subject_course.to_sentence %></h4>
        </div>
        <div class='col-md-1 col-md-offset-2'>
          <button class='rotatecontent btn btn-success' data-container='#<%= dom_id(subject_course) %>'>
            <span class='glyphicon glyphicon-chevron-down'></span>
          </button>
        </div>
      </div>
      <div id='<%= dom_id(subject_course) %>' class='hidden load-on-show subject-course-list-courses-container'
           data-url='<%= group_subject_course_list_courses_path(subject_course) %>'
           data-load-once="true">
      </div>
  <% end %>
</div>

app/views/program/group/_new_group_link_form.html.erb
<%= form_tag program_group_new_path, :method => 'get' do %>
    <%= hidden_field_tag :parent_id, parent.id %>
    <%= hidden_field_tag :parent_type, parent.class.to_s %>
    <%= submit_tag 'Add new', :class => 'btn btn-primary form-control' %>
<% end %>

app/views/program/group/_program_group_edit_list.html.erb
<div class='list-group row-container'>

  <div class="row list-group-item">
    <%= render :partial => 'program/group/new_group_link_form', :locals => {:parent => parent} %>
  </div>
  <% groups.each do |group| %>
      <div class="row list-group-item">
        <div class='col-md-10'>
          <%= render :partial => 'program_group/show', :locals => {:group => group} %>
        </div>
        <div class='col-md-2'>
          <div class='btn-group' style="color: white">
            <div style="display: inline-block">
              <a href="<%= program_group_edit_path(group) %>" class='btn btn-danger' rel="tooltip" data-toggle="tooltip" title="Edit">
                <span class="glyphicon glyphicon-pencil"></span>
              </a>
            </div>
            <div style="display: inline-block">
              <%= form_tag program_group_delete_path do %>
                  <%= hidden_field_tag :id, group.id %>
                  <button class='btn btn-danger' rel="tooltip" data-toggle="tooltip" title="Delete">
                    <span class="glyphicon glyphicon-remove-sign"></span>
                  </button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>

  <% if groups.size > 1 %>
      <div class="row list-group-item">
        <%= render :partial => 'program/group/new_group_link_form', :locals => {:parent => parent} %>
      </div>
  <% end %>
</div>

app/views/program/group/_program_group_list.html.slim
.list-group.row-container
  - groups.each do |group|
    .row.list-group-item
      = render :partial => 'program/group/show', locals: {group: group}

app/views/program/group/_program_group_subject_course_list.html.erb
<div class='list-group'>
  <% group.subject_courses.each do |subject_course| %>
      <div class='list-group-item subject_courses_element'>
        <div class='row'>
          <div class='col-md-10'>
            <%= subject_course.to_s %>
          </div>
          <div class='col-md-2'>
            <div class='btn-group pull-right'>
              <a class='btn btn-danger' href="<%= group_subject_course_list_edit_path(subject_course) %>">
                <span class='glyphicon glyphicon-pencil'></span>
              </a>
              <%= group_button_to group_subject_course_list_delete_path, :class => 'btn btn-danger', :useajax => true, :name => 'id',
                                  :value => subject_course.id, :delete_parent => '.subject_courses_element' do %>
                  <span class='glyphicon glyphicon-remove-sign'></span>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  <div class='list-group-item'>
    <a class='btn btn-primary form-control' href="<%= group_subject_course_list_new_path(:group => group) %>">
      Add new
    </a>
  </div>
</div>

app/views/program/group/_show.html.slim
div
  .container-fluid
    .row
      .col-md-8
        h4 = link_to group.name, group_path(group)
        - group.restrictions.each do |restriction|
          div = t("group.#{restriction.type.to_s}", :value => restriction.value)

      .col-md-4
        = progress_bar_tag group.get_completion_ratio(current_scenario).percent.to_i

  - unless group.courses.empty?
      = render :partial => 'course/course_list', :locals => {:courses => group.courses}

  -unless group.subject_courses.empty?
    = render :partial => 'program/group/group_subject_courses', :locals => {:subject_courses => group.subject_courses}
  - unless group.subgroups.empty?
    hr
    .list-group
      -group.subgroups.each do |subgroup|
        div class="list-group-item"
          = render :partial => 'program/group/show', :locals => {:group => subgroup}